
-- ========================================
-- DATABASE INIT SCRIPT
-- Compiled for submission on: 2025-06-15
-- This script includes schema definitions and data insertions
-- ========================================

-- ========================================
-- SECTION 1: TABLE DEFINITIONS
-- ========================================
CREATE TABLE admins
(
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name                  VARCHAR(255)                            NOT NULL,
    last_name                   VARCHAR(255)                            NOT NULL,
    email                       VARCHAR(255)                            NOT NULL,
    mobile                      VARCHAR(255),
    role                        VARCHAR(255)                            NOT NULL,
    password_reset_token        VARCHAR(255),
    password_reset_token_expiry TIMESTAMP,
    username                    VARCHAR(255)                            NOT NULL,
    password                    VARCHAR(255),
    role_limitation             VARCHAR(255),
    created_at                  TIMESTAMP                               NOT NULL,
    updated_at                  TIMESTAMP                               NOT NULL,
    CONSTRAINT pk_admins PRIMARY KEY (id)
);

CREATE TABLE courses
(
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                       VARCHAR(255)                            NOT NULL,
    description                VARCHAR(1000)                           NOT NULL,
    short_description          VARCHAR(300),
    start_date                 date                                    NOT NULL,
    end_date                   date                                    NOT NULL,
    created_at                 TIMESTAMP                               NOT NULL,
    image_url                  VARCHAR(255),
    capacity                   INT                                     NOT NULL,
    current_bookings           INT                                     NOT NULL,
    min_certification_required VARCHAR(255)                            NOT NULL,
    price                      DECIMAL(10, 2),
    status                     VARCHAR(255)                            NOT NULL,
    featured                   BOOLEAN                                 NOT NULL,
    display_order              INT                                     NOT NULL,
    slug                       VARCHAR(255),
    updated_at                 TIMESTAMP,
    CONSTRAINT pk_courses PRIMARY KEY (id)
);

CREATE TABLE dive_logs
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    dive_number       INT                                     NOT NULL,
    location          VARCHAR(255)                            NOT NULL,
    start_time        time                                    NOT NULL,
    end_time          time                                    NOT NULL,
    dive_date         date                                    NOT NULL,
    duration          INT,
    water_temperature DOUBLE PRECISION,
    air_temperature   DOUBLE PRECISION,
    notes             VARCHAR(2000),
    user_id           BIGINT                                  NOT NULL,
    CONSTRAINT pk_dive_logs PRIMARY KEY (id)
);

CREATE TABLE event_publication
(
    id              UUID NOT NULL,
    completion_date TIMESTAMP,
    CONSTRAINT pk_event_publication PRIMARY KEY (id)
);

CREATE TABLE event_publication_archive
(
    id              UUID NOT NULL,
    completion_date TIMESTAMP,
    CONSTRAINT pk_event_publication_archive PRIMARY KEY (id)
);

CREATE TABLE guest_users
(
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name                  VARCHAR(255)                            NOT NULL,
    last_name                   VARCHAR(255)                            NOT NULL,
    email                       VARCHAR(255)                            NOT NULL,
    mobile                      VARCHAR(255),
    role                        VARCHAR(255)                            NOT NULL,
    password_reset_token        VARCHAR(255),
    password_reset_token_expiry TIMESTAMP,
    dive_certification          VARCHAR(255),
    CONSTRAINT pk_guest_users PRIMARY KEY (id)
);

CREATE TABLE premium_users
(
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name                  VARCHAR(255)                            NOT NULL,
    last_name                   VARCHAR(255)                            NOT NULL,
    email                       VARCHAR(255)                            NOT NULL,
    mobile                      VARCHAR(255),
    role                        VARCHAR(255)                            NOT NULL,
    password_reset_token        VARCHAR(255),
    password_reset_token_expiry TIMESTAMP,
    dive_certification          VARCHAR(255),
    username                    VARCHAR(255)                            NOT NULL,
    password                    VARCHAR(255)                            NOT NULL,
    created_at                  TIMESTAMP                               NOT NULL,
    updated_at                  TIMESTAMP                               NOT NULL,
    CONSTRAINT pk_premium_users PRIMARY KEY (id)
);

CREATE TABLE trips
(
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    location                   VARCHAR(100)                            NOT NULL,
    description                VARCHAR(1000)                           NOT NULL,
    short_description          VARCHAR(300),
    start_date                 date                                    NOT NULL,
    end_date                   date                                    NOT NULL,
    created_at                 TIMESTAMP                               NOT NULL,
    image_url                  VARCHAR(255),
    capacity                   INT                                     NOT NULL,
    current_bookings           INT                                     NOT NULL,
    min_certification_required VARCHAR(255)                            NOT NULL,
    price                      DECIMAL(10, 2),
    status                     VARCHAR(255)                            NOT NULL,
    featured                   BOOLEAN                                 NOT NULL,
    display_order              INT                                     NOT NULL,
    slug                       VARCHAR(200),
    updated_at                 TIMESTAMP,
    CONSTRAINT pk_trips PRIMARY KEY (id)
);

ALTER TABLE admins
    ADD CONSTRAINT uc_admins_password_reset_token UNIQUE (password_reset_token);

ALTER TABLE admins
    ADD CONSTRAINT uc_admins_password_reset_token_expiry UNIQUE (password_reset_token_expiry);

ALTER TABLE admins
    ADD CONSTRAINT uc_admins_username UNIQUE (username);

ALTER TABLE courses
    ADD CONSTRAINT uc_courses_slug UNIQUE (slug);

ALTER TABLE guest_users
    ADD CONSTRAINT uc_guest_users_password_reset_token UNIQUE (password_reset_token);

ALTER TABLE guest_users
    ADD CONSTRAINT uc_guest_users_password_reset_token_expiry UNIQUE (password_reset_token_expiry);

ALTER TABLE premium_users
    ADD CONSTRAINT uc_premium_users_username UNIQUE (username);

ALTER TABLE trips
    ADD CONSTRAINT uc_trips_slug UNIQUE (slug);

CREATE INDEX idx_admin_email ON admins (email);

CREATE INDEX idx_admin_username ON admins (username);

CREATE INDEX idx_guest_user_email ON guest_users (email);

CREATE INDEX idx_guest_user_mobile ON guest_users (mobile);

CREATE INDEX idx_premium_user_email ON premium_users (email);

CREATE INDEX idx_premium_user_username ON premium_users (username);

CREATE INDEX idx_trip_availability ON trips (current_bookings, capacity);

CREATE INDEX idx_trip_certification ON trips (min_certification_required);

CREATE INDEX idx_trip_featured ON trips (featured);

CREATE INDEX idx_trip_location ON trips (location);

CREATE INDEX idx_trip_slug ON trips (slug);

CREATE INDEX idx_trip_start_date ON trips (start_date);

CREATE INDEX idx_trip_status ON trips (status);

ALTER TABLE dive_logs
    ADD CONSTRAINT FK_DIVE_LOGS_ON_USER FOREIGN KEY (user_id) REFERENCES premium_users (id);

-- ========================================
-- SECTION 2: COURSE DATA
-- ========================================
-- Insert 5 courses with 3 can be available for homepage display

INSERT INTO courses (
    name,
    description,
    short_description,
    start_date,
    end_date,
    image_url,
    capacity,
    current_bookings,
    min_certification_required,
    price,
    status,
    featured,
    display_order,
    slug,
    created_at,
    updated_at
) VALUES

-- Course 1: Open Water Diver (will be published)
(
    'Open Water Diver',
    'Start your diving journey with our comprehensive Open Water certification course. Learn essential diving skills including underwater breathing techniques, buoyancy control, underwater navigation, and safety procedures in safe, controlled environments. This course includes pool training sessions, open water dives, and theoretical knowledge development.',
    'Start your diving journey with our beginner-friendly Open Water certification course. Learn essential diving skills in safe, controlled environments.',
    '2025-09-15',
    '2025-09-17',
    '/images/diver-01.JPG',
    12,
    4,
    'NON_DIVER',
    299.00,
    'PUBLISHED',
    true,
    1,
    'open-water-diver',
    NOW(),
    NOW()
),

-- Course 2: Advanced Open Water (will be published)
(
    'Advanced Open Water',
    'Take your diving skills to the next level with specialized training in deep water diving, underwater navigation, night diving, and underwater photography. This course builds upon your Open Water certification and introduces you to new diving environments and techniques through practical adventure dives.',
    'Take your diving skills to the next level with specialized training in deep water, navigation, and underwater photography.',
    '2025-10-05',
    '2025-10-06',
    '/images/AOW.jpg',
    10,
    7,
    'OPEN_WATER',
    399.00,
    'PUBLISHED',
    true,
    2,
    'advanced-open-water',
    NOW(),
    NOW()
),

-- Course 3: Rescue Diver (will be published)
(
    'Rescue Diver',
    'Learn life-saving techniques and emergency response skills to become a confident diver who can help others in challenging situations. This course covers accident prevention, rescue techniques, emergency management, and how to handle dive emergencies both underwater and at the surface.',
    'Learn life-saving techniques and emergency response skills. Become a confident diver who can help others in challenging situations.',
    '2025-10-20',
    '2025-10-23',
    '/images/AOW.jpg',
    8,
    3,
    'ADVANCED_OPEN_WATER',
    499.00,
    'PUBLISHED',
    true,
    3,
    'rescue-diver',
    NOW(),
    NOW()
),

-- Course 4: Nitrox Specialty (will not be published, but available for homepage display,
-- as the display order is above 3)
(
    'Nitrox Specialty',
    'Learn to dive with enriched air nitrox to extend your bottom time and reduce surface intervals. This specialty course covers nitrox theory, gas analysis, dive planning with nitrox, and safety considerations when using enriched air breathing gas.',
    'Learn to dive with enriched air nitrox to extend your bottom time and reduce surface intervals.',
    '2025-11-10',
    '2025-11-10',
    '/images/Nitrox-Enriched-Air-Course.jpg',
    15,
    2,
    'OPEN_WATER',
    149.00,
    'PUBLISHED',
    false,
    4,
    'nitrox-specialty',
    NOW(),
    NOW()
),

-- Course 5: Underwater Photography (The same Logic as Course 4)
(
    'Underwater Photography',
    'Capture the beauty of the underwater world with our comprehensive underwater photography course. Learn camera techniques, lighting, composition, marine life photography, and post-processing skills to create stunning underwater images.',
    'Capture the beauty of the underwater world with our comprehensive underwater photography course.',
    '2025-11-25',
    '2025-11-26',
    '/images/turtle2.JPG',
    6,
    1,
    'OPEN_WATER',
    199.00,
    'PUBLISHED',
    false,
    5,
    'underwater-photography',
    NOW(),
    NOW()
);

-- ========================================
-- SECTION 3: TRIP DATA
-- ========================================
INSERT INTO trips (
    location,
    description,
    short_description,
    start_date,
    end_date,
    image_url,
    capacity,
    current_bookings,
    min_certification_required,
    price,
    status,
    featured,
    display_order,
    slug,
    created_at,
    updated_at
) VALUES -- Trip 1: PUBLISHED - Will appear on web
         (
             'Maldives - Ari Atoll',
             'Discover the breathtaking underwater world of the Maldives with our exclusive diving expedition to Ari Atoll. Experience crystal-clear waters, vibrant coral reefs, and encounters with manta rays, whale sharks, and diverse marine life. This tropical paradise offers some of the best diving conditions in the world with excellent visibility and warm waters year-round.',
             'Explore the pristine coral reefs and encounter manta rays in the crystal-clear waters of Ari Atoll, Maldives.',
             '2025-08-15',
             '2025-08-22',
             '/images/manta-ray.jpg',
             12,
             3,
             'ADVANCED_OPEN_WATER',
             2850.00,
             'PUBLISHED',
             true,
             1,
             'maldives-ari-atoll-2025-08-15',
             NOW(),
             NOW()
         ),

-- Trip 2: PUBLISHED - Will appear on web
         (
             'Red Sea - Sharm El Sheikh',
             'Join us for an unforgettable diving adventure in the Red Sea, one of the world''s most renowned diving destinations. Explore the famous Ras Mohammed National Park, dive the historic SS Thistlegorm wreck, and witness the incredible biodiversity of the Red Sea coral reefs. Perfect for divers seeking both reef and wreck diving experiences.',
             'Dive the legendary Red Sea with wreck exploration and vibrant coral reef encounters in Sharm El Sheikh.',
             '2025-09-10',
             '2025-09-17',
             '/images/dolphin-01.jpg',
             16,
             8,
             'OPEN_WATER',
             1650.00,
             'PUBLISHED',
             true,
             2,
             'red-sea-sharm-el-sheikh-2025-09-10',
             NOW(),
             NOW()
         ),

-- Trip 3: PUBLISHED - Will appear on web
         (
             'Great Barrier Reef - Cairns',
             'Immerse yourself in the wonder of Australia''s Great Barrier Reef, a UNESCO World Heritage site and one of the seven natural wonders of the world. Our Cairns-based expedition offers access to pristine outer reef sites, where you''ll encounter an incredible array of marine life including sea turtles, reef sharks, and countless tropical fish species.',
             'Experience the world-famous Great Barrier Reef with diverse marine encounters and pristine coral formations.',
             '2025-10-05',
             '2025-10-12',
             '/images/bull-shark-01.jpg',
             14,
             2,
             'OPEN_WATER',
             2200.00,
             'PUBLISHED',
             false,
             3,
             'great-barrier-reef-cairns-2025-10-05',
             NOW(),
             NOW()
         ),

-- Trip 4: DRAFT - Will NOT appear on web (still being planned)
         (
             'Palau - Blue Corner',
             'Experience the legendary Blue Corner in Palau, famous for its incredible shark encounters and drift diving. This advanced diving destination offers some of the most thrilling underwater experiences in the Pacific, with massive schools of barracuda, gray reef sharks, and the chance to see hammerhead sharks.',
             'Advanced diving adventure in Palau featuring the world-famous Blue Corner with incredible shark encounters.',
             '2025-11-20',
             '2025-11-27',
             '/images/bull-shark-01.jpg',
             10,
             0,
             'ADVANCED_OPEN_WATER',
             3200.00,
             'DRAFT',
             false,
             4,
             'palau-blue-corner-2025-11-20',
             NOW(),
             NOW()
         ),

-- Trip 5: ARCHIVED - Will NOT appear on web (past trip or cancelled)
         (
             'Thailand - Koh Tao',
             'Discover the diving paradise of Koh Tao, Thailand, known for its affordable diving, excellent training conditions, and abundant marine life. Perfect for beginners and advanced divers alike, with opportunities to see whale sharks, bull sharks, and explore beautiful coral gardens in the warm waters of the Gulf of Thailand.',
             'Explore the diverse dive sites of Koh Tao with excellent conditions for all certification levels.',
             '2025-07-01',
             '2025-07-08',
             '/images/bull-shark-01.jpg',
             18,
             0,
             'OPEN_WATER',
             980.00,
             'ARCHIVED',
             false,
             5,
             'thailand-koh-tao-2025-07-01',
             NOW(),
             NOW()
         );
