services:
  oceandive:
    # Define the service for the OceanDive application
    image: oceandive-dev:v1
    container_name: oceandive-dev
    build:
      context: .  # Set the build context to the current directory
      dockerfile: Dockerfile.dev
    networks:
      - oceandive-network  # Connect to the oceandive-network (internal network)
    volumes:
      - ./src:/app/src  # Mount the entire project directory for live development
      - ./pom.xml:/app/pom.xml  # Mount the Maven POM file
      - ./data:/app/data  # Bind mounts the local ./data directory to /app/data in the container
      - ${HOME}/.m2:/home/devuser/.m2:cached  # Mount Maven cache to the non-root user's home
    ports:
      - "8080:8080"  # Map port 8080 of the host to port 8080 of the container
    environment:
      - SPRING_PROFILES_ACTIVE=dev  # Set Spring profile to development
    # Keep the container running for development
    tty: true
    stdin_open: true

# Define the network for the service
networks:
  oceandive-network:
    driver: bridge
    internal: true  # Makes this network inaccessible from the internet
