services:
  oceandive:
    image: oceandive-dev-image:v1
    container_name: oceandive-dev
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - oceandive-network          # Use the static network name here
    volumes:
      - ./src:/app/src             # Mount source code for live development
      - ./pom.xml:/app/pom.xml     # Maven POM file
      - ${USERPROFILE}/.m2:/home/devuser/.m2:cached # Proper substitution for Maven cache
    ports:
      - "8080:8080"                # Host-to-container port mapping
    environment:
      H2_DATABASE_URL: jdbc:h2:mem:devdb
      H2_DATABASE_USER: sa
      H2_DATABASE_PASSWORD: password
      COMPOSE_BAKE: "true"         # Enable Docker Compose Bake for multi-platform builds

    tty: true
    stdin_open: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  oceandive-network:               # Declare a static network name
    driver: bridge                 # bridge driver for local development
    internal: true                 # Ensure the network is private and not exposed
