spring:
    datasource:
        url: jdbc:h2:file:./data/oceandivedb
        username: sa
        password: password
        driver-class-name: org.h2.Driver
    h2:
        console:
            enabled: true
            settings:
                trace: false
                web-allow-others: true
    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
            hibernate:
                format_sql: true
                use_sql_comments: true
    thymeleaf:
        enabled: true
        mode: HTML
        cache: false
        prefix: classpath:/templates/
        suffix: .html
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
server:
    port: 8080
    servlet:
        context-path: /
logging:
    level:
        com.zaxxer.hikari: DEBUG
        org.springframework.jdbc: DEBUG

# Application specific properties
app:
    upload:
        # For storing images in the database
        dir: ./assets/db_assets

# JWT Configuration
jwt:
    secret: ${JWT_SECRET_KEY}
    issuer: ${JWT_ISSUER}
    audience: ${JWT_AUDIENCE}
    expiration: ${JWT_EXPIRATION_TIME}
    algorithm: ${JWT_SIGNING_ALGORITHM}
    refresh-window: 300  # Time window in seconds before token expiration to consider refreshing
