spring:
  application:
    name: oceandive
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:devdb
    username: sa
    password: password
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        use_sql_comments: true
  h2:
    console:
      enabled: true
      path: /h2-console

  thymeleaf:
    enabled: true
    mode: HTML
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  security:
    oauth2:
      resource server:
        jwt:
          issuer-uri: http://localhost:8080
server:
  port: 8080
  servlet:
    context-path: /oceandive




