spring:
  application:
    name: oceandive
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:dev_db;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      auto-commit: true
      pool-name: HikariPool-1

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  thymeleaf:
    enabled: true
    mode: HTML
    cache: false
    prefix: classpath:/templates/
    suffix: .html

      # security:
      # oauth2:
      # resource server:
      #jwt:
    # issuer-uri: http://localhost:8080
server:
  port: 8080
  servlet:
    context-path: /oceandive
logging:
  level:
    com.zaxxer.hikari: DEBUG
    org.springframework.jdbc: DEBUG




